String? mobileNumber;
String email = '';
String DOB = '';
int? nidNumber;
String? imageLocation;
String? selfieLocation;
String? name;
String? father;
String? mother;
String? presentAddress;
String? permanentAddress;
String nidAsString = "$nidNumber";
String? houseIdentifier;
String? streetAddress;
String? locality;
String? state;
String? postalCode;
String? country;
String? pin1;
String? pin2;
String uri = '103.41.111.51:9103';
